stages:
  - mirror

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 0

mirror_to_github:
  stage: mirror
  before_script:
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git remote add github https://${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/${GITHUB_REPO_NAME}.git
  script:
    - git push github HEAD:main --force
  only:
    - main
  retry: 2